name: frontend

on:
  push:
    branches: [frontend, frontend/**, frontend**]
  pull_request:
    types: [opened, reopened, edited]
    paths: [frontend/**]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache-dependecy-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm run test:ci
